# Generated by Django 5.0.7 on 2024-08-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_post1_photo_post1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
