# Generated by Django 5.0.7 on 2024-08-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_post1_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=1)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_id', models.PositiveIntegerField(unique=True)),
                ('vendor_icon', models.ImageField(blank=True, null=True, upload_to='vendor_icons/')),
                ('question', models.CharField(max_length=200)),
                ('choiceA', models.CharField(max_length=200)),
                ('choiceB', models.CharField(max_length=200)),
                ('choiceC', models.CharField(max_length=200)),
                ('choiceD', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
