# Generated by Django 5.0.7 on 2024-08-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_trip_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Question',
        ),
    ]
