# Generated by Django 5.0.7 on 2024-08-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_remove_question_batch_remove_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='batch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='icon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='route',
            field=models.CharField(default='Default Title', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
