# Generated by Django 5.0.7 on 2024-08-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_question_batch_question_icon_question_route_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
