# Generated by Django 5.0.7 on 2024-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_remove_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Default Vendor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='choiceA',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choiceB',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choiceC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='choiceD',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
