# Generated by Django 5.0.7 on 2024-07-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choiceA', models.CharField(max_length=200)),
                ('choiceB', models.CharField(max_length=200)),
                ('choiceC', models.CharField(max_length=200)),
                ('choiceD', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
