# Generated by Django 5.0.7 on 2024-08-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_post1'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
