# Generated by Django 5.0.7 on 2024-08-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post1',
            name='photo',
        ),
        migrations.AddField(
            model_name='post1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
