# Generated by Django 5.0.7 on 2024-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_rename_vendor_icon_trip_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
