# Generated by Django 5.0.7 on 2024-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_rename_trip_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='route',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
