# Generated by Django 5.1 on 2024-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_post_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
