# Generated by Django 5.1 on 2024-08-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_remove_userprofile_user_gameprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='phone',
            field=models.CharField(default='UNKNOWN', max_length=15),
        ),
    ]
