# Generated by Django 5.1 on 2024-08-13 05:26

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_remove_post_title_post_created_at_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.JSONField(default=trips.models.default_content),
        ),
    ]
