# Generated by Django 5.0.7 on 2024-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
